# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 425d1402c4588461a814621360dd56d9cce19e7f9479b40f259b817615ef378d75cf547e717d4720b50620a3de01a5f2f958ca85802390840a90495e115e425c

test:
  secret_key_base: 668151cf994d6851ac3d2080b66fae51ae3996245e3aeaef8e4a52b353a36df1cc701f8a3f75bf68151f1f2f551512810ed435d3603d4617f536d7ac88558388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
